# Setup redirects

[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true
  conditions = {Country = ["US"]}

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"], Country = ["CA"]}

[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

[[redirects]]
  from = "/"
  to = "/ca-en"
  status = 302
  force = true
  conditions = {Language = ["en"], Country = ["CA"]}

[[redirects]]
  from = "/"
  to = "/ca-en"
  status = 302
  force = true
  conditions = {Country = ["CA"]}