# Rules are applied in order

# If the user has a FR browser, it is redirected to the FR site
[[redirects]]
  from = "/"
  to = "/fr"
  status = 302
  force = true
  conditions = {Language = ["fr"]}

# Every other user is redirected to the EN site.
[[redirects]]
  from = "/"
  to = "/en"
  status = 302
  force = true