backend:
  name: github
  repo: felixdb/cryos-website # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "static/img/uploads" # Folder where user uploaded files should go
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "settings"
    label: "Settings"
    editor:
      preview: false
    files:
      - name: "partenaires"
        label: "Partenaires"
        file: "data/partenaires.yml"
        description: "Vos partenaires, ne pas mettre d'accent dans les noms ou nom de fichier svp!"
        fields:
          - name: partenaires
            label: Partenaires
            widget: list
            create: true 
            fields:
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Image", name: "file", widget: "image"}
      - name: "equipe"
        label: "Membres de l'équipe"
        file: "data/equipe.yml"
        description: "Votre équipe, ne pas mettre d'accent dans les noms de fichier svp!"
        fields:
          - name: equipe
            label: Membre
            widget: list
            create: true 
            fields:
              - {label: "Nom", name: "name", widget: "string"}
              - {label: "Fonction en français", name: "fonction", widget: "string"}
              - {label: "Fonction en anglais", name: "position", widget: "string"}
              - {label: "Ordre", name: "weight", widget: "number"}
              - {label: "Image", name: "photo", widget: "image"}
  - name: "articles" # Used in routes, e.g. /admin/collections/blog
    label: "Articles" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Rating (scale of 1-5)", name: "rating", widget: "number"}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "cliniques-fr" # Used in routes, e.g. /admin/collections/blog
    label: "Cliniques FR" # Used in the UI
    folder: "content/location" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom de la clinique", name: "nomclinique", widget: "string"}
      - {label: "Adresse", name: "address", widget: "string", default: "Numéro et nom de rue"}
      - {label: "Ville et province", name: "ville", widget: "string", default: "Montréal, Québec, H2R 2R5"}
      - {label: "Pays", name: "pays", widget: "string", default: "Canada"}
      - {label: "Latitude", name: "latitude", widget: "number"}
      - {label: "Longitude", name: "longitude", widget: "number"}
      - {label: "Numéro de téléphone", name: "phone", widget: "string"}
      - {label: "Site internet", name: "site", widget: "string", pattern: ["^https?", "N'oubliez pas le http:// ou https://"]} 
      - {label: "Type", name: "type", widget: "hidden", default: "location"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
  - name: "cliniques-en" # Used in routes, e.g. /admin/collections/blog
    label: "Cliniques EN" # Used in the UI
    folder: "content/location" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}.{{i18nlanguage}}"
    filter: 
      field: "i18nlanguage"
      value: "en"
    fields: # The fields for each document, usually in front matter
      - {label: "Nom de la clinique", name: "nomclinique", widget: "string"}
      - {label: "Adresse", name: "address", widget: "string", default: "Numéro et nom de rue"}
      - {label: "Ville et province", name: "ville", widget: "string", default: "Montréal, Québec, H2R 2R5"}
      - {label: "Pays", name: "pays", widget: "string", default: "Canada"}
      - {label: "Latitude", name: "latitude", widget: "number"}
      - {label: "Longitude", name: "longitude", widget: "number"}
      - {label: "Numéro de téléphone", name: "phone", widget: "string"}
      - {label: "Site internet", name: "site", widget: "string", pattern: ["^https?", "N'oubliez pas le http:// ou https://"]} 
      - {label: "Type", name: "type", widget: "hidden", default: "location"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}